version: '3.8'

services:
  weather-bot:
    build: .
    pull_policy: build
    restart: unless-stopped
    environment:
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      LATITUDE: ${LATITUDE}
      LONGITUDE: ${LONGITUDE}
      WIND_FORCE_THRESHOLD: ${WIND_FORCE_THRESHOLD}
      UPDATE_INTERVAL: ${UPDATE_INTERVAL}
